In [1]:
import numpy

In [2]:
numpy.__version__

'1.14.3'

In [3]:
import numpy as np

## Python List的特点

In [4]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L[5]

5

In [6]:
L[5] = "ML"

In [7]:
L

[0, 1, 2, 3, 4, 'ML', 6, 7, 8, 9]

In [8]:
import array
arr = array.array("i", [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5]

5

In [10]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [11]:
arr[5] = "1"

TypeError: an integer is required (got type str)

## numpy.array

In [12]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr[5]

5

In [14]:
nparr[5] = 100

In [15]:
nparr[5]

100

In [16]:
nparr[5] = "1"

In [17]:
nparr[5]

1

In [18]:
nparr[5] = "a"
nparr[5]

ValueError: invalid literal for int() with base 10: 'a'

In [19]:
nparr.dtype

dtype('int32')

In [20]:
nparr[5] = 5.0

In [21]:
nparr[5]
nparr.dtype

dtype('int32')

In [22]:
nparr[3] = 3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
nparr2 = np.array([1, 2, 3.0])

In [24]:
nparr2.dtype

dtype('float64')

## Other

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10).dtype

dtype('float64')

In [29]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.full(shape=(3, 5), fill_value=666.0)

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

In [41]:
np.full(fill_value=666.0, shape=(3, 5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange

In [42]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [46]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [48]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [49]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [50]:
np.random.randint(0, 10)

0

In [51]:
np.random.randint(0, 10, 10)

array([6, 2, 1, 6, 7, 7, 1, 5, 9, 2])

In [52]:
np.random.randint(4, 8, size=10)

array([5, 5, 6, 7, 5, 4, 5, 7, 5, 4])

In [54]:
np.random.randint(4, 8, size=(3, 5))

array([[5, 4, 5, 4, 6],
       [4, 5, 4, 7, 7],
       [4, 4, 4, 7, 6]])

In [55]:
np.random.seed(666)

In [56]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [57]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [59]:
np.random.random()

0.7744794542685887

In [60]:
np.random.random(10)

array([0.00510884, 0.11285765, 0.11095367, 0.24766823, 0.0232363 ,
       0.72732115, 0.34003494, 0.19750316, 0.90917959, 0.97834699])

In [62]:
np.random.random((3, 5))

array([[0.53280254, 0.25913185, 0.58381262, 0.32569065, 0.88889931],
       [0.62640453, 0.81887369, 0.54734542, 0.41671201, 0.74304719],
       [0.36959638, 0.07516654, 0.77519298, 0.21940924, 0.07934213]])

In [71]:
np.random.normal()

0.06706964821543099

In [69]:
np.random.normal(10, 100)

-20.236751995176004

In [67]:
np.random.normal(0, 1, (3, 5))

array([[ 0.44325817, -1.66738875, -1.81731749, -1.39753916,  0.78392691],
       [-0.29129965,  0.67049043,  0.706931  ,  1.42965241, -0.41407013],
       [-1.32672274, -0.14880188,  0.34771289,  0.61030791, -1.17532603]])

In [72]:
np.random.normal?

In [73]:
np.random?

In [74]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap