In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target
X.shape

(150, 4)

In [5]:
y.shape

(150,)

### train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 98, 111, 103,  72,   1, 112,  82,  26,  81, 113, 123,  32,  60,
        55,  96, 148,  99,  83,  33,  12,  80, 134,  35,  59,  36,  93,
       106,  65, 118,  43, 116,   6,  61,  94,  14, 120,   0,   3,  79,
        48, 141,  89,  76,  19,  85,  44, 104,  13,  52, 144,  66, 117,
       100,  53, 131,  11, 128,  78, 110,  31,  28, 129, 109,  38,  70,
        57, 142, 138, 115,  45, 102,  69,  90,  30,  24,  23, 122, 149,
       130,  73,  47,  10,   2,  58,  77, 127,  21, 136, 126,  50, 101,
        87,  68,  95,  63,  75, 145,  91,  74,  22,  15,  34,  25, 107,
       135,  62,  27,  56,  37, 133, 139,  88,  49,  16,  92,  46,   7,
        39, 140,  51, 137, 147, 119,  54,  20,  29,  42,  71, 114,   8,
        40,  64,  67,  18, 143,   4, 146,   9,  17, 132,  97, 125, 108,
       124,  41, 105,   5,  86,  84, 121])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [12]:
test_indexes = shuffle_indexes[:test_size]

In [11]:
train_indexes = shuffle_indexes[test_size:]

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
import model_selection

In [18]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)


(120, 4)
(120,)


In [25]:
from kNN import KNNClassifier

In [27]:
my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [28]:
y_predict = my_knn_clf.predict(X_test)

In [29]:
y_predict

array([1, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 2, 1,
       1, 0, 0, 0, 0, 2, 1, 0])

In [30]:
y_test

array([1, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 1, 2, 2,
       1, 0, 0, 0, 0, 2, 1, 0])

In [31]:
sum(y_predict == y_test)

29

In [32]:
sum(y_predict == y_test)/len(y_test)

0.9666666666666667

### sklearn

In [33]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 666)

In [35]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)
