In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.01260115, 0.24234864, 0.66375345, 0.54550327, 0.42035361,
       0.306514  , 0.93614045, 0.5334824 , 0.83209804, 0.08729521,
       0.81865142, 0.65635883, 0.74290789, 0.32468987, 0.25494573,
       0.72578014, 0.09597976, 0.8423986 , 0.88712843, 0.02276052,
       0.47594809, 0.51291041, 0.12839565, 0.49066457, 0.80836722,
       0.66836104, 0.36567979, 0.57052546, 0.67084303, 0.11205729,
       0.32711099, 0.8735524 , 0.65085312, 0.33156782, 0.92504366,
       0.11022461, 0.85655355, 0.11711957, 0.30570602, 0.79002653,
       0.60980767, 0.9171101 , 0.40683696, 0.47212044, 0.34576403,
       0.36858947, 0.7965766 , 0.95502238, 0.12241331, 0.95535858,
       0.39303412, 0.14385539, 0.02066111, 0.04914531, 0.56026974,
       0.00424632, 0.76829558, 0.56530459, 0.56563527, 0.03981414,
       0.88833089, 0.06166183, 0.96240563, 0.22769923, 0.98788634,
       0.18477745, 0.3915059 , 0.44736281, 0.47305135, 0.73903146,
       0.10934945, 0.97609893, 0.35454297, 0.49441189, 0.46989

In [3]:
sum(L)

46.506541034609725

In [4]:
np.sum(L)

46.50654103460973

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

157 ms ± 582 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
982 µs ± 24.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

7.759503856119565e-07

In [7]:
np.max(big_array)

0.9999977250167812

In [8]:
big_array.min()

7.759503856119565e-07

In [9]:
big_array.max()

0.9999977250167812

In [10]:
big_array.sum()

499706.81065808516

In [11]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)

0

In [16]:
np.prod(X + 1)

2004189184

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)

0.4999433084007897

In [23]:
np.median(big_array)

0.4999433084007897

In [24]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

7.759503856119565e-07
0.24937157952489364
0.4999433084007897
0.7496407527038652
0.9999977250167812


In [25]:
np.var(big_array)

0.08328070146413241

In [26]:
np.std(big_array)

0.2885839591247795

In [27]:
x = np.random.normal(0, 1, size=1000000)
np.mean(x)

0.00018413138716837186

In [28]:
np.std(x)

1.0000737503254777

### 索引

In [29]:
np.min(x)

-4.653402204015487

In [30]:
np.argmin(x)

360675

In [32]:
x[360675]

-4.653402204015487

In [33]:
np.argmax(x)

107564

### 排序和使用索引

In [34]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
np.random.shuffle(x)
x

array([ 3,  2, 13, 12,  6,  0, 15,  4, 14,  8, 10,  5,  7,  1,  9, 11])

In [36]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x

array([ 3,  2, 13, 12,  6,  0, 15,  4, 14,  8, 10,  5,  7,  1,  9, 11])

In [38]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
X = np.random.randint(10, size=(4, 4))
X

array([[2, 3, 8, 1],
       [6, 1, 7, 6],
       [0, 1, 6, 3],
       [1, 3, 3, 5]])

In [40]:
np.sort(X)

array([[1, 2, 3, 8],
       [1, 6, 6, 7],
       [0, 1, 3, 6],
       [1, 3, 3, 5]])

In [41]:
np.sort(X, axis=1)

array([[1, 2, 3, 8],
       [1, 6, 6, 7],
       [0, 1, 3, 6],
       [1, 3, 3, 5]])

In [42]:
np.sort(X, axis=0)

array([[0, 1, 3, 1],
       [1, 1, 6, 3],
       [2, 3, 7, 5],
       [6, 3, 8, 6]])

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
np.random.shuffle(x)

In [45]:
x

array([15, 13,  4,  0,  5,  7,  9, 11,  8,  2,  3, 12, 10, 14,  1,  6])

In [46]:
np.argsort(x)

array([ 3, 14,  9, 10,  2,  4, 15,  5,  8,  6, 12,  7, 11,  1, 13,  0],
      dtype=int64)

In [47]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  6,  5,  7,  8,  9, 10, 11, 12, 14, 13, 15])

In [48]:
np.argpartition(x, 3)

array([ 3, 14,  9, 10,  2, 15,  4,  5,  8,  6, 12,  7, 11, 13,  1,  0],
      dtype=int64)

In [49]:
X

array([[2, 3, 8, 1],
       [6, 1, 7, 6],
       [0, 1, 6, 3],
       [1, 3, 3, 5]])

In [50]:
np.argsort(X, axis=1)

array([[3, 0, 1, 2],
       [1, 0, 3, 2],
       [0, 1, 3, 2],
       [0, 1, 2, 3]], dtype=int64)

In [51]:
np.argsort(X, axis=0)

array([[2, 1, 3, 0],
       [3, 2, 2, 2],
       [0, 0, 1, 3],
       [1, 3, 0, 1]], dtype=int64)

In [52]:
np.argpartition(X, 2, axis=1)

array([[3, 0, 1, 2],
       [1, 0, 3, 2],
       [0, 1, 3, 2],
       [0, 1, 2, 3]], dtype=int64)